# Generated by Django 4.1.2 on 2022-10-06 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('author', models.DecimalField(decimal_places=0, max_digits=10)),
                ('header_img', models.FileField(blank=True, null=True, upload_to='blog_headers/')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
