# Generated by Django 4.1.2 on 2022-10-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blog_remove_user_categories_remove_user_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('blog', models.DecimalField(decimal_places=0, max_digits=10)),
                ('parent_id', models.DecimalField(decimal_places=0, default=-1, max_digits=10)),
                ('about', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='cat_icons/')),
                ('posts', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
    ]
