# Generated by Django 4.1.2 on 2022-10-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lang',
            field=models.CharField(default='en', max_length=12),
        ),
    ]
