# Generated by Django 4.1.2 on 2022-10-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blog_slug_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.DecimalField(decimal_places=0, default=-1, max_digits=10),
        ),
    ]
