# Generated by Django 4.1.2 on 2022-10-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lang',
            field=models.CharField(default='en', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='lang',
            field=models.CharField(default='en', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='lang',
            field=models.CharField(max_length=12),
        ),
    ]
