# Generated by Django 4.1.2 on 2022-10-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blog_lang_category_lang_alter_post_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='blog_icons/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='blog',
            field=models.DecimalField(decimal_places=0, default=-1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='lang',
            field=models.CharField(default='en', max_length=12),
        ),
    ]
